version: '2'
linters:
  default: none
  enable:
    - durationcheck
    - errcheck
    - forcetypeassert
    - govet
    - ineffassign
    - makezero
    - misspell
    - nilerr
    - predeclared
    - sloglint
    - staticcheck
    - unconvert
    - unparam
    - unused
  settings:
    sloglint:
      attr-only: true
      context: all
      key-naming-case: snake
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
issues:
  max-same-issues: 0
formatters:
  enable:
    - gofmt
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
