# Visit https://golangci-lint.run/ for usage documentation
# and information on other useful linters
issues:
  max-same-issues: 0

linters:
  disable-all: true
  enable:
    - durationcheck
    - errcheck
    - exportloopref
    - forcetypeassert
    - gofmt
    - gosimple
    - ineffassign
    - makezero
    - misspell
    - nilerr
    - predeclared
    - staticcheck
    - tenv
    - unconvert
    - unparam
    - unused
    - vet
    - sloglint
linters-settings:
  sloglint:
    # Enforce using attributes only (overrides no-mixed-args, incompatible with kv-only).
    attr-only: true
    # Enforce using context methods on logger. This is very useful for us because it means we
    # can easily integrate with the tflog package in terraform and pipe all log output correctly.
    context-only: true
    # Enforce a single key naming convention.
    # Values: snake, kebab, camel, pascal
    # Default: ""
    key-naming-case: snake