linters:
  disable:
    - exportloopref  # deprecated since Go 1.22
    - tenv          # deprecated, replaced by usetesting
  enable:
    - copyloopvar   # replacement for exportloopref
    - usetesting    # replacement for tenv

issues:
  max-issues-per-linter: 0
  max-same-issues: 0

run:
  timeout: 5m
  
output:
  format: colored-line-number