# Terraform Provider testing workflow.
name: Tests

on:
  push:
    paths-ignore:
      - 'README.md'
    branches:
      - 'main'
  pull_request:
    paths-ignore:
      - 'README.md'
    branches:
      - 'main'
  workflow_dispatch:

# Testing only needs permissions to read the repository contents.
permissions:
  contents: read

jobs:
  # Ensure project builds before running testing matrix
  build:
    name: Build
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
          cache: true
      - run: go mod download
      - run: go build -v .
      - name: Run linters
        uses: golangci/golangci-lint-action@v5
        with:
          version: latest
          args: --timeout=10m

  generate:
    name: Generate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
          cache: true
      # Temporarily download Terraform 1.8 prerelease for function documentation support.
      # When Terraform 1.8.0 final is released, this can be removed.
      - uses: hashicorp/setup-terraform@651471c36a6092792c552e8b1bef71e592b462d8 # v3.1.1
        with:
          terraform_version: '1.8.0-alpha20240216'
          terraform_wrapper: false
      - run: go generate ./...
      - name: git diff
        run: |
          git diff --compact-summary --exit-code || \
            (echo; echo "Unexpected difference in directories after code generation. Run 'go generate ./...' command and commit."; exit 1)

  # Run unit tests
  unit-test:
    name: Terraform Provider Unit Tests
    needs: build
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
          cache: true
      - run: go mod download
      - run: go test -v -timeout=30m -cover ./internal/provider/

  opentofu-test:
    name: OpenTofu Compatibility Tests
    needs: build
    runs-on: ubuntu-latest
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        tofu-version:
          - '1.6.0' # Latest stable OpenTofu version
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
          cache: true

      # Install OpenTofu
      - name: Install OpenTofu
        run: |
          curl -SL https://github.com/opentofu/opentofu/releases/download/v${{ matrix.tofu-version }}/tofu_${{ matrix.tofu-version }}_linux_amd64.zip -o tofu.zip
          unzip -o tofu.zip  # Use -o flag to overwrite files without prompting
          chmod +x tofu
          sudo mv tofu /usr/local/bin/
          tofu version

      # Run basic compatibility tests
      - name: OpenTofu Provider Compatibility Check
        run: |
          # Build provider binary in repo root (where go.mod is)
          cd $GITHUB_WORKSPACE
          go build -o terraform-provider-megaport

          # Create test directory and move there
          mkdir -p /tmp/opentofu-test
          cd /tmp/opentofu-test

          # Create development override file
          mkdir -p ~/.terraform.d/plugins
          cat > ~/.terraformrc << 'EOL'
          provider_installation {
            dev_overrides {
              "megaport/megaport" = "$GITHUB_WORKSPACE"
            }
            direct {}
          }
          EOL

          # Create test config
          cat > main.tf << 'EOL'
          terraform {
            required_providers {
              megaport = {
                source = "megaport/megaport"
                version = ">=0.0.0"
              }
            }
          }

          provider "megaport" {
            environment = "staging"
            # For tests, we don't need real credentials
            access_key = "test"
            secret_key = "test"
            accept_purchase_terms = true
          }
          EOL

          # Set up local plugin directory
          mkdir -p .terraform/plugins/registry.terraform.io/megaport/megaport/0.0.1/linux_amd64
          cp $GITHUB_WORKSPACE/terraform-provider-megaport .terraform/plugins/registry.terraform.io/megaport/megaport/0.0.1/linux_amd64/terraform-provider-megaport_v0.0.1
          chmod +x .terraform/plugins/registry.terraform.io/megaport/megaport/0.0.1/linux_amd64/terraform-provider-megaport_v0.0.1

          # Test OpenTofu with the provider
          cp ~/.terraformrc ~/.tofurc
          tofu init
          tofu providers

          echo "OpenTofu compatibility test completed successfully"

  # TODO: reenable these once we get a better public workflow for PRs
  # # Run acceptance tests in a matrix with Terraform CLI versions
  # test:
  #   name: Terraform Provider Acceptance Tests
  #   needs: build
  #   runs-on: ubuntu-latest
  #   timeout-minutes: 30
  #   strategy:
  #     fail-fast: false
  #     matrix:
  #       # list whatever Terraform versions here you would like to support
  #       terraform:
  #         - '1.7.*'
  #         - '1.8.*'
  #   steps:
  #     - uses: actions/checkout@v4
  #     - uses: actions/setup-go@v5
  #       with:
  #         go-version-file: 'go.mod'
  #         cache: true
  #     - uses: hashicorp/setup-terraform@651471c36a6092792c552e8b1bef71e592b462d8 # v3.1.1
  #       with:
  #         terraform_version: ${{ matrix.terraform }}
  #         terraform_wrapper: false
  #     - run: go mod download
  #     - env:
  #         TF_ACC: "1"
  #         MEGAPORT_ACCESS_KEY: ${{ secrets.MEGAPORT_ACCESS_KEY }}
  #         MEGAPORT_SECRET_KEY: ${{ secrets.MEGAPORT_SECRET_KEY }}
  #       run: go test -v -timeout=30m -cover ./internal/provider/
